digitalrebar/provision

tools/drbundler
tools/install.sh

and use the catalog to get the proper versions.
Create a deprated drbundler that can be installed
that will work but show deprecation.

Update install.sh to work with the new v4 locations

---

tools/install.sh

saas-content, the default content layer went away.

Put the drp-community-content pack directly into the

---

tools/install.sh

Created a DRP_HOME_DIR = /var/lib/dr-provision
Replaced all instances of the hard coded path
with that variable.
Created BIN_DIR = /usr/local/bin
Replaecd all instanes of the hard coded path
with this variable.

replaced 2 harded coded paths with variables

---

tools/install.sh

Making changes to installer to support being installed
to run as non root user.
This change adds 2 functions to the installer
1. setup_system_user
This checks if its root and returns, or makes a system
group and user using the provided --system-{user/group}
params.
2. set_ownership_of_drp
This changes ownership of $DRP_HOME_DIR to the
system-user:system-group

Making installer support non root user

---

tools/install.sh

This fixes the lack of `setcap` during a non-isolated, non-root install. The binary is only setcapped if `--system-user` is not `root`.
I also found a couple further issues when looking into the `setcap` issue:
* `groupadd` and `adduser` commands were not called with `$_sudo`
* Return code of `adduser` was not checked correctly, so script would silently exit if user already existed
* If user already existed (e.g. pre-created), then `${DRP_HOME_DIR}` is not automatically created - and ends up with the wrong permissions set, causing startup issues.
* `set_ownership_of_drp` was running too early, meaning upgrade commands might create subdirectories of the homedir owned by root. This now runs after these, to set the permissions correctly.

Fix various install sh issues

---

tools/install.sh

Added some missing Env vars to systemd

---

tools/install.sh

Make sure the install.sh sets the ownership of the binaries

---

tools/install.sh

Allow of non-root users to set bin-dir for upgrades

Reorder things so that bin-dir can be setup.

---

tools/install.sh

Moves the drp startup check into a function, and allows it to work when `upgrade` mode is selected (since `drpcli info get` requires a login if the default user has been deleted).
This avoids attempting to create the DRP user when running in upgrade mode, which fails and causes the script to exit nonzero.
Finally, this fixes a compatibility issue with Bash 4.1+ when incrementing the `COUNT` variable in the drp check loop where it exits prematurely (see [here](https://stackoverflow.com/questions/6877012/incrementing-a-variable-triggers-exit-in-bash-4-but-not-in-bash-3) for further info)

Do not attempt to create system user on upgrade

---

models/machine.go

Goodbye, Machine.Profile.

---

cli/catalog.go
cli/metaHelper.go
cli/paramHelper.go
cli/startup.go
cli/test-data/output/TestCorePieces/gohai.0c113ca6d57519b559ba5a426be3c6b6/stdout.expect
cli/utils.go
go.mod

the remote catalog.  The remote catalog is the default catalog
with the normal override of -c.
Additionally add the download http proxy flag to allow for
downloading the catalog and content through the specified http proxy.

Add catalog localUpdate to update the local catalog with

---

doc/integrations/ansible.rst
doc/setup/aws.rst
integrations/ansible/drpmachines.py

Simple addition that picks up the Profile.Profiles feature dynamically.
Will still respect the params approach.

Ansible use profile in profile feature

---

cli/startup.go

Make the added element the first in the list (not the second from the

---

doc/setup/aws.rst
doc/setup/linode.rst

tweak install docs to show stable, not tip as default

doc should pull stable not tip

---

doc/setup/aws.rst
doc/setup/linode.rst

also use the stackscripts for Linode

Improve docs with wait loop for machines

---

tools/install.sh

- fix exit_clenaup to exit_cleanup
- fix passowrd to password

Fix typos in install.sh

---

tools/install.sh

- clean up if/else/fi statements with case and functions
- remove 7zip dependency
- add new `--container` flag to install container
- additional container flags:
+ `--container-name` - set container name
+ `--container-type` - (only "docker" supported currently)
+ `--container-vol` - set backing volume name for container
+ `--container-registry` - set alternate registry location to pull container images
- add OS_FAMILY detection support for CoreOS - calls `--container` install type

Add CoreOS and Generic Docker container install support

---

tools/install.sh

Add bootstrap option to install.sh to store install pieces in

---

tools/install.sh

Add new `--container-env` flag to customize the Environment variables passed in to DRP during install and start up.
Example usage:
`curl -s get.rebar.digital/tip | bash -s -- install --container --container-env="RS_METRICS_PORT=8888 RS_BINL_PORT=1104"`

Add '--container-env' flag to installer

---

tools/install.sh

- enhance fallback to `bsdtar` if `tar` extract fails
- try local binary if exists, if not, try and install it
- better notifications on trying to recover

Enhance 'tar'/'bsdtar' handling

---

tools/install.sh

Adds network namespace configuration to the `install.sh` script.  Defaults to `host`.  Tested to work with default (nothing specified), with `host` set to manually specify, and with an invalid network namespace (`foobar` - which chucks an error and fails to load the container since the namespace isn't available).

Add network namespace option to container start

---

doc/integrations/ansible.rst
integrations/ansible/drpmachines.py

General pep8 cleanups
Added debug logging
Updated docs to reflect the new debug option

Updated the drpmachines.py script

---

cli/files.go
cli/prefs.go
doc/cli_commands.rst
doc/faq-troubleshooting.rst
doc/integrations/ansible.rst
doc/rackn/license-no-images.rst
doc/rackn/license.rst

updates to the RackN license process reflecting changes for v4 and automation.

docs - update license instructions

---

doc/setup/linode.rst
doc/setup/packet.rst

takes advantage of catalog install

Packet install docs

---

plugin/plugin.go

This allows plugins to switch to using websockets + selective event recieve instead of having their own dedicated event recieve endpoint and no filtering.

Let plugins be selective about the events they recieve

---

doc/operation.rst
doc/operations/contexts.rst

Added runbook style doc to get up and running with docker-context

Added operational docs for docker-context

---

doc/faq-troubleshooting.rst

needed when building Ansible templates in Jinja2

Docs for Brace Protection

---

tools/install.sh

--create-self - creates a self machine object for this DRP server in DRP.
--start-runner - starts an internal runner for the DRP machine
--start-runner implies create-self.
Both only function for systemd-based systems.

Update install.sh to support two new flags.

---

doc/arch/provision.rst
doc/features.rst

minor tweak to add something about contexts

updates to docs

---

doc/operation.rst
doc/operations/imagedeploy.rst

Initial draft of an operations based doc for image based deployments.

added operations doc for image deploy

---

doc/faq-troubleshooting.rst

makes it easier to find password info for all platforms.
xref to https://github.com/digitalrebar/provision-plugins/pull/93

add VMware password to FAQ

---

doc/faq-troubleshooting.rst
doc/quickstart.rst

- add new FAQ section on Manager requirement on Clock Time being consistent
- fix minor formatting consistency in FAQ for sections (two lines before `.. _rs_*:` tags)
- add references for all JQ faqs; fix `rs_filter_gohai` to be consistent with other JQ FAQs (`rs_jq_filter_gohai`)

Add Manager clock time, consistency for sections

---

README.rst
doc/install.rst
doc/operations/runbooks.rst
doc/upgrade.rst

Enhance docs:
* install steps cleanup, add container based install
* upgrade doc - rework it to be correct
* add references for `drbup` related pages
* reorder main ToC contents to put install/upgrade next to each other

Update install and upgrade documents.

---

doc/faq-troubleshooting.rst

* faq had incorrect systemd example - fix the `[Service]` tag to be correct

Fix FAQ doc for 'drp-id' setting in systemd

---

doc/faq-troubleshooting.rst

minor update to FAQ based on recent UX updates

add-key via UX

---

doc/faq-troubleshooting.rst

Added instructions to update sledgehammer when updating community-content

added step to faq doc for sledgehammer

---

README.rst
doc/arch/data.rst
doc/cli.rst
doc/dev/dev-contributing.rst
doc/dev/dev-docs.rst
doc/faq-troubleshooting.rst
doc/high-availability.rst

I've added some details to help people with HA installations.
Also, added other doc items
* how to download the CLI
* required -install in bootenv

doc: update HA docs to include troubleshooting

---

doc/install.rst

Updated the install docs to fix formatting issues.

docs(install): Updated the install doc

---

doc/operation.rst
doc/operations/esxi-getting-started.rst

added new operations doc for getting started with ESXi

doc(esxi-getting-started): added new ops doc

---

api/client.go

Many things need the PROXY not be turned on like it is.
The proxy is fine for a singleton runner on a lone machine,
but for testing environments and within the server, the proxy
gets in the way.

feat(api): allow for NO PROXY token and user sessions

---

models/plugin_provider.go

Make sure PluginProvider.Fill() adds an empty StoreObjects field
instead of leaving it nil.

fix(pluginProvider): PluginProvider.Fill was missing StoreObjects.

---

doc/arch/models.rst

docs for https://github.com/rackn/provision-ux/pull/917

docs(params): document clipboard param meta field, fix incorrect downloadable docs

---

cli/bootenv.go

This API call will purge any local install data for a bootenv (isos
and install trees) on an arch by arch basis.

feat(bootEnv): Add CLI support for the new purgeLocal API endpoint

---

doc/ux/portal/controlux.rst
doc/ux/portal/endpointadminux.rst
doc/ux/portal/networkingux.rst
doc/ux/portal/provisionux.rst
doc/ux/portal/syncuploadux.rst

* remove switches section from networking
* remove outdated filter header button references
* update content catalog section
* update support files section

doc day - portal ux docs fixes

---

doc/setup/esxi.rst

Added a page to explain what the setup of an ESXi test machine would look like

docs(added ESXi setup doc)

---

doc/quickstart.rst
doc/setup/preparing.rst

Adds information on PoC/Trial/Test users and new production users to understand some of the basic requirements and preparation to successfully use DRP.

enhance(doc): Add 'preparing' document for new users

---

doc/setup/hyper-v.rst

Adds detailed description on how to build a DRP environment
targeted at Hyper-V for Windows 10 Pro or Enterprise. Can be
adapted to work with Hyper-V Hypervisor as well. Builds a complete
lab environment with a target machine and a DRP Endpoint using
the stable branch installer. The endpoint runs on a Debain 10
Virtual Machine, and one or more target Virtual Machines. The
target instaces are network isolated to allow for reproduction
of other environments with conflicting IP space.

docs: Add example configuration for Hyper-V environment

---

conf.py
doc/release.rst

This has lots of errors for the moment.  It will get better.

docs: more release notes

---

doc/setup/kvm.rst

- Adds environment setup document for KVM

enhance(doc): Add KVM Setup environment document

---

doc/setup/kvm.rst

- fix broken RST in title
- add example install for DRP
- fix spelling

bug(doc): Fix KVM  RST Doc

---

tools/docs-make-kb.sh

- fixes the LABEL that is generated based on the TITLE

fix(docs): Fix KB generator script 'label'

---

api/bootenv_test.go

Server-side will no longer emit spurious template processing errors.

fix(bootenvTest): Fix up to match current serverside reporting

---

doc/kb/kb-00009.rst

Fix the table formatting for the default passwords table.

bug(doc): Fix KB-00009 table format

---

doc/rel_notes/summaries/release_v40.rst
doc/rel_notes/summaries/release_v41.rst
doc/rel_notes/summaries/release_v42.rst
doc/rel_notes/summaries/release_v43.rst
doc/rel_notes/summaries/release_v44.rst
doc/rel_notes/summaries/release_v45.rst
doc/release.rst

Copied v4.4 release notes into doc area
Copied over past release notes as available

doc(provision): add current and previous release summaries

---

README.rst
doc/rel_notes/summaries/release_v40.rst
doc/rel_notes/summaries/release_v41.rst
doc/rel_notes/summaries/release_v42.rst
doc/rel_notes/summaries/release_v43.rst
doc/rel_notes/summaries/release_v44.rst
doc/rel_notes/summaries/release_v45.rst

updated release links in main doc

doc(releases): xref for releases

---

doc/operation.rst
doc/operations/bios.rst

- add BIOS operations documentation

enhance(doc): Add BIOS Operations doc

---

doc/faq-troubleshooting.rst
doc/integrations/terraform.rst

also catches reference to moved documentation

doc(terraform): update terraform provider docs

---

doc/kb/kb-00045.rst

- add KB article with details on supported image types

enhance(doc): Add KB for supported image deploy image types

---

doc/kb/kb-00046.rst

Added a kb article to cover the ExtraClaims

doc(ExtraClaims): Added kb about ExtraClaims

---

cli/startup.go
cli/support.go

Added initial support bundle creator for failed drp instances

feat(drpcli): added initial support bundle command

---

doc/kb/kb-00047.rst

- adds a Knowledge Base introduction to basic Git usage with Digital Rebar

doc(kb): Add KB on basic Git Usage

---

doc/cli.rst
doc/cli/drpcli.rst
doc/kb/kb-00042.rst
doc/rel_notes/summaries/release_v45.rst

create place to collect deprecation information ahead of the next release.

doc(provision): add deprecation warning to v4.5 release

---

doc/kb/kb-00047.rst

doc(kb47): updated info to use fork-branch wf

---

api/client.go

This adds a new Context() method to the c.Req() API that allows passing in
a Context to help control request timeouts and deadlines.
See https://golang.org/pkg/context/ for more information on how to
use Contexts.

feat(cancel): Add context.Context support to the API.

---

doc/kb/kb-00049.rst

Added kb for how to enable EPEL

doc(kb): added epel doc

---

doc/kb/kb-00049.rst

Updated KB article with review suggestions

doc(kb) updated epel kb article

---

doc/cli.rst

- enhances the initial `drpcli` download to support different OS/Arch/Ver of drpcli

doc(cli): Add more comprehensive download script for getting drpcli

---

doc/kb/kb-00034.rst

doc(kb): updated wget doc to include example

---

cli/startup.go
cli/support.go

Drpcli support logs

---

doc/kb/kb-00049.rst
doc/operations/drpcli.rst

Added support bundle info for drpcli and also a kb article on how to update drpcli

doc(drpcli): added support bundle info and kb

---

doc/integrations/terraform.rst

With TF 0.13, new required syntax

@zehicle doc(provision): update terraform to include required_providers

---

doc/high-availability.rst

Our HA support is designed around a couple of key assumptions, and violating
those assumptions can lead to data loss, wailing, and gnashing of teeth.
Add a section to the documentation outlining when you should not use our
integrated HA support.

doc(high-availability): Add contraindication section to documentation.

---

README.rst
conf.py
doc/arch.rst
doc/kb/kb-00042.rst
doc/operation.rst
doc/operations/drpcli.rst
doc/upgrade.rst
models/whoami.go

fix(models): move embedded struct in Wmoami to named struct

doc: tweaks and fixes

---

doc/rel_notes/summaries/release_v45.rst

missed feature of note from the v4.5 release

doc(release-notes): add missed WAL backup feature

---

go.mod
go.sum

This adds fixed support for old redhat initscripts network config.

fix(net): Pull in latest netwrangler changes.

---

doc/arch/design.rst

doc(api): fix godoc link

---

doc/arch/design.rst
doc/operations/security.rst

@zehicle doc(provision): add more questions and answers to security FAQ

---

store/file.go

This brings it in-line with all the other Store types.

fix(store): Have the file Store set Name on open.

---

doc/operations/security.rst
doc/rel_notes/summaries/release_v46.rst

pre-populate v4.6 feature information including TLS flag

doc(provision): backport note for TLS flag

---

doc/operations/contexts.rst

docs to support for UX Wizard helping people setup docker-contexts.

doc(docker-context): add section for files location and podman

---

doc/arch/dhcp.rst
doc/kb/kb-00052.rst

Based on discussions with community and prospects, these are common questions.

doc(provision): reasons why to use DRP DHCP

---

README.rst
doc/arch/cluster-pre46.rst
doc/arch/cluster.rst
doc/kb/kb-00052.rst

Document cluster pattern
includes other small cleanups

doc(task-library): document v4.6 cluster pattern

---

doc/arch/data.rst

captured additions to the template extensions.

@zehicle doc(dr-server): include new .Params options in docs

---

doc/operations/manager.rst

enhance the Multi-Site Manager Operations documentation with more API/CLI/Portal references.  Add notices/warnings about licensing.

enhance(doc): MSM operations updates

---

doc/arch/provision.rst
doc/kb/kb-00055.rst
doc/rel_notes/summaries/release_v46.rst

based on notes from community support
and RackN deliverables for release.

doc(provision): troubleshooting KB and release note updates

---

doc/kb/kb-00057.rst

doc(param precedence): added kb for param precedence

---

doc/arch/workflow.rst

doc(workflow): added idempotent doc

---

doc/operations/esxi-getting-started.rst

docs(vmware): updating the esxi gsg

---

doc/rel_notes/summaries/release_v3x.rst
doc/rel_notes/summaries/release_v40.rst
doc/rel_notes/summaries/release_v41.rst
doc/rel_notes/summaries/release_v42.rst
doc/rel_notes/summaries/release_v43.rst
doc/rel_notes/summaries/release_v44.rst
doc/rel_notes/summaries/release_v45.rst
tools/install.sh

minor fix (plus version bump) to include AMZN family.
includes tweaks to Release Notes.

refactor(provision): Install.sh works on on AMZN vm

---

cli/system.go
go.mod
go.sum
models/ha-state.go
models/utils.go

This includes the client side changes for HA enrollment and management.

Ha consensus api models and enrollment

---

doc/operations/backup.rst

doc(backup): updated dr-waltool doc

---

doc/setup/kvm.rst
tools/vm-bridge.sh

working on streamlined first install videos
having this accessible as a curl bash script is helpful

doc(install): move vm bridge script into runnable location, update docs

---

cli/agent.go
go.mod
go.sum

For boith of those init systems, just log everything through stderr
instead of trying to go through syslog for everything.

fix(agent): Remove reliance on syslog for systemd and upstart.

---

doc/kb/kb-00060.rst

Adds a knowledge base articles on how to work with Secure Params.

enhance(doc): Add KB for Secure Params

---

doc/high-availability.rst
doc/rel_notes/summaries/release_v46.rst

Preparing for release.  Lost some items in "other items" - I'll do another patch after I recreate.
minor fixes to HA docs and I'm testing.

doc(provision) updates to release notes for v4.6

---

doc/arch/dhcp.rst

doc(dhcp): added note about reservations

---

doc/rel_notes/summaries/release_v46.rst

keeping up with features included in the v4.6 release

doc(provision): release note additions

---

agent/agent.go
agent/taskRunner.go

Test in Travis have been intermittently failing, apparently due to
timing issues between when a process ends and when its stdout and
stderr get flushed.  Close these by using an alternate wait strategy.

fix(agent): Hopefully fix weird test failures due to log flushing.

---

doc/install.rst
doc/upgrade.rst

Adds downgrade procedural notes to the Upgrade/Downgrade documentation.

enhance(doc): Add Downgrade procedure

---

doc/arch/provision.rst
doc/rackn/license-pre46.rst
doc/rackn/license.rst
doc/rel_notes/summaries/release_v46.rst

Also, include .ParamCompose in template docs.

doc(provision): update for new license processes

---

cli/system.go

The API has been vetted, expose it in dr-provision.
There may still be changes made to the behaviour of the API.

feat(consensus): Add node removal command in drpcli

---

cli/system.go
doc/rel_notes/summaries/release_v46.rst

+ formatting fix for release notes list

doc(drpcli): clearify, remove uses consensusid not endpointid

---

agent/agent.go
api/bootenv.go
api/client.go
cli/catalog.go

reversed conditional fix for tokens.

fix(goland): Some correctness fixes from Goland, and a stupid

---

doc/operation.rst
doc/operations/imagedeploy-storage.rst
doc/operations/imagedeploy.rst

Start collecting the Image Deploy `curtin/partitions` examples in a single Operations document.

enhance(doc): Image Deploy Storage Examples

---

doc/operations/imagedeploy-storage.rst

Adds more examples for `curtin/partitions`.  Also fixes the `:ref:` links.

enhance(doc): Update curtin/partitions with more

---

tools/install.sh

* Add `initial-subnets` option, plus usage note that Subnets can be added as content packs
* clean up usage notes a bit with more details
* add safety check for `initial-workflow` to not overwrite `universal` option set initial workflow
* add safety/fixes around IFS processing to restore OLD IFS value after twiddling it
* add file based handling for fully qualified path to files causing uploads to break
* add a couple of more echo outputs about things that are happening that are hidden behind `> /dev/null`

enhance(installer): Add subnets, small fixes

---

tools/install.sh
tools/update-installer.sh

Try out the installer:
curl -fsSL https://raw.githubusercontent.com/digitalrebar/provision/feat-install-colors/tools/install.sh | bash -s -- install --systemd --version=stable
or try out the new colorized usage:
curl -fsSL https://raw.githubusercontent.com/digitalrebar/provision/feat-install-colors/tools/install.sh | bash -s -- --help

WIP - feat(installer): colorize the installer, add cleaner output

---

doc/high-availability.rst
doc/rackn/license.rst

minor update to include training videos

doc(provision): add links to training videos

---

doc/kb/kb-00065.rst

Added KB article to outline where to get the OLB's and how to generate a the bootenv and templates when using them

doc(kb): Added kb for vmware custom iso

---

doc/quickstart.rst

Added firewalld command and link to server arch for ports.
Signed-off-by: Nathan Conlon <nathanec@gmail.com>

doc(Quickstart): Added firewall info.

---

doc/arch.rst
doc/arch/whoami.rst
doc/dev/dev-curl.rst
doc/rel_notes/summaries/release_v48.rst
models/machine.go
models/whoami.go

include CloudInstanceID in the Machine.Fingerprint
Includes doc updates related to supporting this feature.

feat(cloud-wrapper): resolve cloud-init with whoami lookup

---

api/info_test.go
cli/files.go
models/info.go
test/server_darwin.go
test/server_linux.go

Adds support for HTTPS  static file serving on a dedicated port

feat(https-file-server): Add info settings for HTTPS static file server

---

agent/taskRunner.go

This allows the incomplete to be honored whenever we also want to reboot, shutdown, or have the agent exit, no matter the
rest of the exit state and where we are in processing templates for a task.

fix(agent): Fix handling of task incomplete and reboot.

---

cli/catalog.go

https://github.com/rackn/product-backlog/issues/24

WIP - allow catalog updateLocal defaults to ignore tip unless explicitly set and get only stable versions

---

cli/catalog.go
go.mod
go.sum

https://github.com/rackn/product-backlog/issues/22

WIP: feat(cli): allow concurrent catalog updates

---

cli/profileHelper.go

https://github.com/rackn/product-backlog/issues/38

WIP: fix(cli): Fix addprofile removeprofile cli messages to reference appropriate type

---

cli/profileHelper.go

https://github.com/rackn/product-backlog/issues/38

WIP: fix(cli): o.name is already plural - machines, stages, profiles

---

cli/jobs.go

Add several flags to `jobs purge` to allow for more selective job
purging and reporting.  Additional functionality is gated behind a
server feature flag to prevent misunderstandings and accidental loss
of data.

feat(jobs): Extend jobs purge functionality.

---

cli/catalog.go
cli/contents.go
cli/machines.go
cli/netwrangle.go
cli/plugin_providers.go

Related to: https://github.com/rackn/provision-server/pull/605

WIP: fix(flags): hyphenated flags for per command flags

---

tools/install.sh

Updates to the `install.sh` script:
* documentation reordering, and renaming separation between `options` and `arguments`
* forcibly reorder ARGs to put `--universal` first if it appears in the ARGv list
* fix direct call to `drpcli` to go through `_drpcli` internal function

enhance(installer): Document cleanup, enable '--universal' in any ARG position

---

doc/operations/esxi-getting-started.rst

doc(esxi): Updated getting started guide to clean
