digitalrebar/provision

Dockerfile
=> installer doesn't install bundler anymore - it is deprecated.

tools/install.sh
This fixes installation of `drpcli` in docker containers where:
- We already are root
- `sudo` is not present
Cheers
=> Don't try to become root if we already are. Warn if sudo is not present.

tools/install.sh
`adduser` on rhel systems was not passed a username to create, and also complains about the usergroup already existing unless `--gid <groupname>` is passed
=> Fix broken adduser with no name passed

tools/install.sh
Added missing env variable to the systemd file to allow
installs to be anywhere on the file system. Now what ever
is set for `--drp-home-dir=` will be set as RS_BASE_ROOT
with a default of `/var/lib/dr-provision`
=> added RS_BASE_ROOT to systemd file

tools/install.sh
Mistakenly added Environment= to the PermissionsStartOnly option
=> Added Environment by mistake

agent/agent.go, api/objects_test.go
This changes the wait code to ensure that an agent running on the
"real" machine will always reboot if a bootenv changes, no matter what
other context is running.  Other contexts will no longer care about
bootenv changes.
=> Make BootEnv changes always trigger a reboot.

models/catalogItem.go, tools/install.sh
Update jq to not use bsdtar and not require jq.
This requires tar and the "zip" file to be tgz.
=> Add NOJQSource to the catalog for use in install.sh without jq.

tools/install.sh
sudo if logic test failed if non-root, but sudo executable was in the PATH
=> fix logic test for sudo check

doc/faq-troubleshooting.rst
- adds `.rsclirc` FAQ notes for human formatter outputters (table/text)
- adds new FAQ section specifically for formatter details
=> Human output formatter FAQ additions

tools/install.sh
There were several bugs in the behavior in the `install.sh` script.  Some cleanups around usage() as well.
* add usage warning that `install` over writes existing installation
* remove gratuitous `touch` which causes zero length files
* fix `for` loop to `chown`, with `|| true` to prevent error exit
* add `export RS_ENDPOINT=https://127.0.0.1:8092` - on DRP endpoint managed systems, DRP endpoint install tests will fail or behave inconsistently since they are testing the managing DRP, not he service currently being installed
* correctly fix restore of `drpcli` backup binary (for systems under existing DRP endpoint control)
* fix directory checks before trying to remove them
=> Fixes to install.sh

models/machine.go, models/templateInfo.go
to other files in the filesystem.  This allows for dynamic
names to static files.  This is needed for certain hardware
types.
Also, allow for the fake arch rpi4.  It is a lie, but lets
us handle certain badness that the rpi4 has.
=> Start of new feature.  BootEnv templates can contain links

doc/arch.rst
Community pointed out missing link to doc. This patch adds the missing link.
=> Added doc path for arch/data

cli/catalog.go
Initial adding of the create catalog feature. This allows a user to set
a catalog source and select a version "stable" or "tip" and a smaller
catalog will be generated using only that selected version.
Usage: drpcli catalog create --pkg-version stable > stable.json
This would pull the default catalog from repo.rackn.io and build a new
catalog of only "stable" marked packages.
=> Added the create catalog feature

tools/install.sh
- `install.sh` can now upgrade an existing DRP installed docker container version
- can also remove the container, and honors the `--remove-data` flag semantics
NOTES:
If you are upgrading an existing docker container, and you have customized the start up options and configuration of your original container - you MUST USE the same `install` flags with the `upgrade` arguments.  There is no state preserved to be able to easily determine how the original install process was called.
=> install.sh learns how to upgrade and remove docker containers

integrations/ansible/drpmachines.py
This change will skip adding a machine to the inventory if the
machine name or the ip adddress is empty. This keeps context
runners out of the inventory, as well as other pseudo machines.
This change also introduces the ability to define a param named
anisble_user
If set then that value will be used to override both root default,
and the shell env.
=> update drpmachines.py to skip empty machines

integrations/ansible/drpmachines.py
This fixes an error introduced in the previous commit which allowed the user to be set.
The user was never reset on the next loop iteration making an expected value be used.
=> Fixing error in ansible dynamic inventory

doc/arch/provision.rst, tools/install.sh
The installation for self bootstrap agent was always creating the agent even if it was not flagged.  This ensures correct behavior.
Also, add some supporting template expansion fields to the docs.
=> catch Install flag correctly

doc/arch/data.rst, doc/faq-troubleshooting.rst
I had some other typos I was going to fix in `doc/content-packages/drp-community-content `, but the .gitignore file ignores `/doc/content-packages/*.rst `for some reason. So git doesn't acknowledge my changes to the file, and then sphinx build reverts the changes back.
The doc contributing guidelines didn't specify a preferred branch to receive PRs
=> Doc: Fix 2 typos

.gitignore, conf.py
Place files in doc-override and they will be copied after
the download of S3 files.
=> feat(doc): Allow for content-packages to be overriden.

tools/docs-indexer.sh
Part of creating searchable documentation through the UX involved creating plaintext documentation with file indices. This is the tool that does that.
Depends on ruby, automatically runs `make json` if `_build/json` does not exist
Outputs to stdio as a giant json blob consisting of:
{
"path/to/docfile": "docfile contents in plaintext",
...
}
At the moment that blob is around 2.2MB
=> Tool for generating indexed blob of entire docs

doc/arch/provision.rst, doc/faq-troubleshooting.rst, doc/operation.rst, doc/operations/scaling.rst, doc/operations/security.rst
This migrates over the RackN security FAQ
Also creates a placeholder for the scale doc
Expanded the ops ToC to include subsections.
=> doc(security): migrate security faq from internal to shared docs

cli/machines.go, cli/startup.go, go.mod, go.sum, models/machine.go, models/role.go, models/whoami.go
Add the required models and machine code changes to allow for detcting
what Machine record most closely matches the current running machine.
Currently, this is based on a combination of matching certian classes of
DMI information, memory serial numbers, and MAC address matching.
This will eventually allow dr-provision to be resilient in the face
of hardware changes when running tasks.
=> feat(fingerprint): machine fingerprint models and Gohai updates

doc/quickstart.rst
- update quickstart to specify DRP Endpoint service can not run on Windows
=> doc(quickstart): Fix references about Windows

tools/install.sh
The problem
-
When trying to run the install.sh script, The script reports an error saying that the OS is unsupported. I'm installing this on Raspbian; which given a lot of the blog posts I see about digital rebar say it's compatible with a raspberry pi, is odd.
What this PR aims to achieve
-
This commit allows for Rasberry Pis to be used for the provisioning service. I found that Updating the install.sh and adding `raspbian` to line 307 seems to allow for a seamless install.
=> Update install.sh to allow for Raspberry pi install.

doc/arch/data.rst
- docs had incorrect references for `.Machine.URL` - correct is `.Machine.Url`
- docs had incorrect references for `.Env.InstallURL` - correct is `.Env.InstallUrl`
yes - inconsistent with `.ProvisionerURL`
=> bug(doc): Fix URL -vs- Url incorrect refs in doc.

go.mod, go.sum, models/whoami.go
Sigh, in the face of cloned vms and such we cannot really rely on
certian parts of the DMI information being unique enough to count for
fingerprint purposes.  To alleviate that, don't calculate uniqueness
hashes based on DMI information when we are dealing with something we
know is running under a hypervisor, and fall back to doing uniqueness
checking based just on mac addresses
=> fix(whoami): Account for vms running under hypervisors not being unique

models/whoami.go
So, it turns out there are lists of known lying serial and asset
information that we should filter out when calculating a fingerprint.
Filter that stuff out.
=> fix(whoami): Ignore obviously terrible DMI information

go.mod, go.sum, models/bootenv.go, models/utils.go
We need a mechanism to allow for dynamic override of bootenvs to reign
in the bootenv explosions being caused by ESXi and others, and to
allow for user customizations of bootenvs that do not result in having
to copy everything that uses those bootenvs.
Along the way, switch to using deepcopy instead of JSON for model
cloning purposes.
=> feat(override-bootenvs): Add basic bootenv override functions.

tools/install.sh
In most testing, I've set the drp-ip.  If the ID is not set, then the drp-id and the self runner names do NOT match.
this coverts the ID to the correct name by replacing : with -
=> bug(provision): install.sh create-self ID does not match runner name

doc/quickstart.rst
Fixed command example in the quickstart guide from a *get* to a *list*
=> doc(quickstart): fixed typo in quickstart command

doc/kb/kb-00010.rst
- fixes the RST table rendering for the `.drpclirc` knowledge base article (KB-00010)
=> bug(doc): Fix RST table rendering for KB-00010 - .drpclirc

tools/docs-make-kb.sh
- bash 5 related `printf` casts the "46" to a number then fails to zero pad as String type
- change type to decimal (`%0d`) to make it better
=> fix(docs-make-kb): Type correct printf fix

LICENSE.rst, api/content.go, api/contents_test.go, cli/catalog.go, cli/contents.go, cli/plugin_providers.go
The content pack and plugin upload API paths have added support for allowing the content that the objects provide
to replace identically named objects in the local writable store.  Multiple other layers providing identically named objects
is still disallowed.
=> feat(replaceWritable): Content packs can now override writable data

doc/setup/kvm.rst
* wrap heredoc terminator in single quotes to prevent interpolation on the initial evaluation
* fix script name for output
* add missing mode to script `chmod`
=> bug(doc): fix KVM vm creation helper script

doc/kb/kb-00034.rst, doc/kb/kb-00046.rst
- enhance the portfast KB for multiple options specified (space separated, no commas)
- fix kb-00046 RST formatting
=> fix(doc): Enhance portfast, fix KB 46 RST

doc/kb/kb-00048.rst
Adds knowledge base article describing content pack upload error with an error for Unicode "dash" (U+002D).
=> doc(kb): Add KB on content unicode dash error

cli/info.go
The server-side code has gotten a little bit stricter about rejecting
invalid DHCP packets, including ones that do not have a chaddr set.
Add a fake one to our probing packets.
=> fix(dhcpTest): Add a MAC address to our test DHCP packets.

models/tenant.go, models/utils.go
models.New was making one of everything on every call, despite being
obligated to only return one thing.  Use a bit of reflection and
init time caching to stop generating excess garbage.
=> perf(models): Stop generating excess garbage in models.New()

api/client.go, cli/plugin_providers.go
This PR allows you to control both initial connect timeouts and
per-request total response timeouts using the context.Context mechanism.
It also adds support for downloading plugin_providers.
=> feat(timeouts):  Allow more granular control over API timeouts.

doc/high-availability.rst
This adds documentation for the --ha-interface and
--ha-interface-script commandline options to dr-provision.  The former
controls what interface we will use for HA failover purposes, and the
latter allows for overriding dr-provision's internal IP address
management.
=> doc(ha): Add documentation for ha interface configuration.

README.rst
The godoc badge is currently broken unless a user has accepted the cookie that redirects to `pkg.go.dev`. This fixes the link directly.
=> doc: Link godoc to pkg.go.dev. Fix badge.

README.rst, conf.py, doc/rel_notes/summaries/release_v40.rst, doc/rel_notes/summaries/release_v41.rst, doc/rel_notes/summaries/release_v42.rst, doc/rel_notes/summaries/release_v43.rst, doc/rel_notes/summaries/release_v44.rst, doc/rel_notes/summaries/release_v45.rst, doc/rel_notes/summaries/release_v46.rst, doc/release.rst
Primarily, this is an update for the v4.5 release notes
It includes some cleanups on other pages and the addition of the v4.6 placeholder.
=> doc(provision): release notes for v4.5

doc/api.rst, doc/arch/manager.rst, doc/operations/manager.rst
capturing the API call for the proxy create case. 
left breadcrumbs in other docs.
=> doc(multi-site-manager): add docs for proxy creates

cli/agent.go, go.mod, go.sum
It is overly strict about determining what init system it is using,
causing detection to fail in cases where the service install environment
is not the same as the enviropnment in which the service will be started.
=> fix(agent): Switch to using a hard fork of the service package.

doc/rel_notes/summaries/release_v42.rst, doc/rel_notes/summaries/release_v43.rst, doc/rel_notes/summaries/release_v44.rst, doc/rel_notes/summaries/release_v45.rst, doc/rel_notes/summaries/release_v46.rst, doc/release.rst, doc/security/cve_20200924A.rst
Documents CVE 20200924a: Web requests can navigate outside of DRP controlled areas
========================================================================
DRP server incorrectly respects using `..` for navigation if resulting path is outside of managed areas.  This potentially allowed bad actors to access the host file system.
* Classification: Directory Traversal
* Reported: Sept 24, 2020
* Fixed: Sept 24, 2020
* Addressed In: v4.5, v4.4.7, v4.3.8, v4.2.17
Recommendation
--------------
Users are advised to apply this patch as soon as possible.   Patching involves replacing the DR-SERVER binary that closes matches the currently deployed version.
Mitigation
----------
Code was added to prevent out of bounds navigation.
Steps to reproduce
------------------
:: 
docker run --rm -it ubuntu …
=> doc(provision-server): document cve20200924a

doc/kb/kb-00008.rst
Fixes the table formatting for KB-00009 (SSH user/pass Auth).
=> fix(doc): fix kb-00009 (ssh auth) table formatting

doc/arch/runner-state.rst, doc/kb/kb-00054.rst, doc/operation.rst, doc/operations/security.rst, doc/operations/virtualmedia-iso-booting.rst
Adds new documentation for the _Technical Preview_ feature for VirtualMedia ISO Booting via the out-of-band controller path.
- Adds an operations/virtualmedia-iso-booting documentation page
- Creates an index in the operations.html reference TOC
- Adds a Knowledge Base regarding the general topic
Additional Doc clean up from certain peoples not verifying their RST is good, and adds reference indexes for `runner-state`.
=> doc(virtualmedia-iso-booting): Add Ops and KB articles for VirtualMedia ISO Booting, minor cleanups

api/client.go, api/event_stream.go, cli/contents.go, cmds/drbundler/drbundler.go, doc/api.rst, plugin/plugin.go
This adds a logger.Logger to the API client for various things to use.  Over time. the client-side code that uses the log package should be converted to use this instead.
=> Messing around with client logging

cli/support.go
Added the abort log to the support bundle should it exist
=> feat(drpcli): added abort log to support bundle

cli/system.go, doc/high-availability.rst
This expands the HA documentation to include information on the
new raft-based consensus protocol, along with instructions on
bootstrapping a consensus cluster from a standalone server.
=> feat(consensus): Update HA docs to include consensus docs.

README.rst, doc/api.rst, doc/arch.rst, doc/arch/cluster-pre46.rst, doc/arch/provision.rst, doc/arch/runner-state.rst, doc/kb/kb-00025.rst, doc/operation.rst, doc/operations/backup.rst, doc/operations/security.rst, doc/security/cve_20200924A.rst, doc/upgrade.rst
Fix many extra trailing spaces, bad reference links, title levels, closing elements, etc.
=> fix(doc): Fix many doc formatting and x-ref errors

doc/rel_notes/summaries/release_v46.rst
Documents the DEPRECATION of the Linux `base` workflows (eg `centos-7-base`, `debian-10-base`) for Linux OS installations.
These workflows will be removed in a future version of DRP.  The replacement deployment solution is to use the `universal-linux-install` workflow.  Please see Knowledge Base article #00061 for more details.
=> enhance(doc): v4.6 release notes, linux 'base' workflows deprecated

doc/kb/kb-00061.rst
Adds Knowledge Base article with quick instructions on how to use the `universal-linux-install` workflow as a replacement for the now Deprecates Linux base install workflows.
NOTE: This introduces a Swagger break for `:ref: rs_cp_universal` - this will be resolved when the Universal content pack documentation is pulled in to the build system and released to RTD.
=> enhance(doc): Add universal linux install KB article

doc/kb/kb-00062.rst, doc/rel_notes/summaries/release_v46.rst
Adds Knowledge Base article to help troubleshoot why Ubuntu 20.04 autoinstall doesn't start.
Additionally fix Release Notes v4.6 link `:ref:` tag.
=> enhance(doc): Add Ubuntu 20.04 autoinstall rendering troubleshooting KB

doc/kb/kb-00063.rst, doc/rel_notes/summaries/release_v46.rst
Adds Knowledge Base article on how to work with the HTTP/S File server via `drpcli`, `wget`/`curl`, and in golang templating.
Also fixes Release Notes bad RST reference to Universal Content documentation.
=> enhance(doc): Add KB on HTTP/S File Server use

agent/agent.go, api/client.go
The client can panic of Close() is called on it multiple times, which
can be the case if several independent routines are using the same api
CLient and they both close the Client as part of cleanup.  Fix the
issue be refactoring the code to use a Context for closing instead.
While we are at it, have the agent refresh its token on a regular
schedule.
=> fix(race): Fix client panic on multiple Close()

api/client.go, cli/contents.go, cli/machines.go, store/common.go
Instead of bailing and killing the program when token refresh fails for
any reason, back off and try again up to 5 times with decreasing intervals,
and give up while closing the client if the final refresh fails.  This
should lead to better behaviour on intermittent communication failures
while still forcing things to exit eventually.
=> fix(token): Make the background token refresh goroutine error tolerant.

doc/kb/kb-00064.rst
Knowledge Base article that explains how to use rendering within Tasks/Templates to enable `drpcli` access to the DRP Endpoint and API.
=> enhance(doc): Add KB on rendering for drpcli in Workflow use

tools/install.sh
Adds support to `install.sh` for DRP Endpoint installation.  Tested on Photon 3 and 4 versions.
`tip` installer script has been updated to this version (eg `curl -s get.rebar.digital/tip`).
=> enhance(installer): Add Photon Linux support for DRP Endpoint install.

cli/jobs.go
This command will purge all jobs in accordance with the per-machine
job retention preferences and all jobs not associated with a machine.
=> feat(jobs): Add jobs purge command.

models/modtimesha.go
Add a GenerateStat() method to ModTimeSha to allow passing in
pre-fetched stat() information instead of fetching it anew.  This is
intended to use when we are already doing lots of work on the
filesystem we are storing data on, and want to minimize the number
syscalls and potential disk seeks we get.
=> feat(modtimesha): Add GenerateStat()

tools/update-installer.sh
Adds updater script to push the `install.sh` to the S3 bucket.  Example usage (defaults to Source input file of `tools/install.sh`):
```
tools/update-installer.sh -d stable,tip
```
Requires `aws` command line tool at 2.2.5 or newer for Mac OS X output to work correctly.
Includes all the latest rage in colorized textual output.
MUST set AWS credentials either via `$HOME/.aws/credentials`, or appropriate Shell Variables, eg:
```
export AWS_ACCESS_KEY_ID=key
export AWS_SECRET_ACCESS_KEY=secret
```
OR use of `-k key` and `-p password` flags to the script.
=> enhance(add): Add update installer script for 'install.sh'

cli/machines.go
My attempt to resolve the hard-coded reference to the C: drive when installing the drpcli agent and providing the default state location. Using the path/filepath module since the Join function also fixes the slashes separating the folder names to whatever is appropriate for the underlying OS.
Instead of using a hard-coded reference to C:\Windows, I am  suggesting to replace it with whatever the value of the SYSTEMROOT environment variable is.
=> Added work-around to hard-coded drive letter for Windows drpcli

models/license.go
Adds a single field, ContractTerminationDate, for meta data from the licensing platform. Only purpose at the moment is for storage and eventual display in the Portal.
=> feat(license): add contract termination date field

agent/taskRunner.go
This pull request contains two suggestions to the taskRunner functions:
- It adds support for the `ExecutionPolicy` parameter to allow the drpcli agent to run PowerShell scripts, even if the machine's execution policy settings require that scripts be digitally signed. This approach does not change the machine's configuration and only applies to the specific script being executed as part of the task.
- This commit adds support for Windows batch scripts with the file extensions of `.bat` and `.cmd`.
This commit does make a change to the way the task file itself is being added the to CommandContext which affects all currently supported operating systems. The reason for this is that Linux and Windows use different folder separators in file paths. By using the `filepath.FromSlash` function, it …
=> Two improvement suggestions for the taskRunner functions with regard to Windows

doc/install/install.rst
Fix the install doc to not reference use of `unzip`, which is incorrect.  The `dr-provision.zip` file is actually a tar.gz format file, despite the filename extension.
=> fix(doc): Fix install doc reference to use 'unzip'

api/bootenv_test.go
Patch errors from dr-provision now include the full patch, instead of
just the patch line.
=> fix(patch): More detailed patch errors

doc/api.rst, doc/cli/drpcli.rst, doc/operations/drpcli.rst, doc/rel_notes/summaries/release_v47.rst, doc/rel_notes/summaries/release_v48.rst, doc/rel_notes/summaries/release_v49.rst
Roadmap updates for v4.7+
Clarify API uses Swagger for docs.
=> doc(provision): update advance release notes, tweak api docs

tools/install.sh
- Tested locally.  Removes only files expected.  Passed.
- Tested with /usr/local/bin/jq as a regular file.  Does not remove it.  Passed.
- Tested with /usr/local/bin/jq as a link to /root/blah.  Does not remove it.  Passed.
=> fix(installer): remove more binaries

doc/dev/dev-server.rst
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> docs: deprecate very old section about building digital rebar ui

cli/startup.go, cli/test-data/output/TestCorePieces/gohai.0c113ca6d57519b559ba5a426be3c6b6/stdout.expect
Deprecate and hide the camelCased persistent flags.  This should also
be done for the per-command flags.
=> fix(flags) Start standardizing on hyphenated flags.
